# Generated by Django 4.1.1 on 2022-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('created_dates', models.DateTimeField(auto_now_add=True)),
                ('updated_dates', models.DateTimeField(auto_now_add=True)),
                ('deleted_dates', models.DateTimeField(null=True)),
            ],
        ),
    ]
